<?php
declare(strict_types=1);
require __DIR__.'/includes/ui.php';
$u=msw_require_user();msw_bot_simulation_pulse(null,10);$summary=msw_bot_population_summary();$maps=msw_map_catalog();$biomes=msw_fob_biome_catalog();
$fobDist=[];foreach(msw_all("SELECT w.biome_key,COUNT(*) c,COUNT(DISTINCT w.id) shards FROM bot_commanders b JOIN fob_world_memberships m ON m.user_id=b.user_id JOIN fob_worlds w ON w.id=m.world_id WHERE b.enabled=1 GROUP BY w.biome_key ORDER BY w.biome_key") as $r)$fobDist[(string)$r['biome_key']]=['count'=>(int)$r['c'],'shards'=>(int)$r['shards']];
$rows=msw_all("SELECT u.id,u.username,u.character_key,u.active_map,u.map_x,u.map_y,u.level,u.base_grade,u.base_power,b.*,m.world_id,m.slot_index,w.biome_key,w.shard_index FROM bot_commanders b JOIN users u ON u.id=b.user_id LEFT JOIN fob_world_memberships m ON m.user_id=u.id LEFT JOIN fob_worlds w ON w.id=m.world_id WHERE b.enabled=1 ORDER BY COALESCE(b.last_action_at,b.created_at) DESC,b.bot_index ASC LIMIT 80");
$chars=msw_character_catalog();msw_header('AI Commander Network','ai_commanders.php');?>
<section class="hero"><div class="eyebrow">PERSISTENT AUTONOMOUS COMMAND NETWORK</div><h1>1,000 <span>AI COMMANDERS</span></h1><p>Every autonomous commander is a persistent database identity using the same selectable Metal Slug operative skins, warzone collision, Commander progression, recovered-unit roster, Mother Base sectors, resource ledger, sharded FOB placement and PvP combat model as a human account. Bots can be invaded by players and now scout the global FOB network themselves: immediate and staff-dispatch raids occur more often, can cross shard boundaries, and may target human commanders as genuine competitors. Their field-action cadence and XP gains are modestly accelerated so the shared rankings develop at a more visible persistent pace without turning each page request into an unbounded simulation job.</p></section>
<div class="grid g3" style="margin-top:18px"><?php foreach($maps as $key=>$map):$count=(int)($summary['maps'][$key]??0);?><article class="panel"><div class="panel-body"><span class="badge">Threat <?=intval($map['level'])?></span><h3><?=msw_e($map['name'])?></h3><div class="stat"><small>Autonomous Commanders</small><strong><?=number_format($count)?></strong><em>Persistent warzone population</em></div><a class="btn small secondary" href="<?=msw_e(msw_url('map.php?zone='.urlencode($key)))?>">Deploy Here</a></div></article><?php endforeach;?></div>
<?php msw_panel('Autonomous FOB Distribution','SHARDED GLOBAL OVERVIEW');?>
<div class="grid g4"><?php foreach($biomes as $key=>$entry):$d=$fobDist[$key]??['count'=>0,'shards'=>0];msw_stat($entry['name'],number_format($d['count']),$d['shards'].' active shard'.($d['shards']===1?'':'s'));endforeach;?></div>
<?php msw_panel_end();?>
<?php msw_panel('Autonomous Activity','LATEST 80 COMMANDERS');?><table><thead><tr><th>AI Commander</th><th>Warzone</th><th>FOB World</th><th>Lv</th><th>Base</th><th>Activity</th><th>Stats</th></tr></thead><tbody><?php foreach($rows as $r):$c=$chars[$r['character_key']]??reset($chars);$worldLabel=!empty($r['world_id'])?strtoupper((string)$r['biome_key']).'-'.str_pad((string)(int)$r['shard_index'],3,'0',STR_PAD_LEFT):'UNPLACED';?><tr><td><a href="<?=msw_e(msw_url('profile.php?id='.(int)$r['id']))?>" style="color:#c9f0ff">#<?=intval($r['bot_index'])?> <?=msw_e($r['username'])?></a><br><small><?=msw_e($c['name'])?></small></td><td><?=msw_e($maps[$r['active_map']]['name']??$r['active_map'])?><br><small><?=intval($r['map_x'])?>, <?=intval($r['map_y'])?></small></td><td><?=msw_e($worldLabel)?><br><small>Slot <?=intval($r['slot_index']??-1)+1?></small></td><td><?=intval($r['level'])?></td><td><span class="grade"><?=msw_e($r['base_grade'])?></span> <?=number_format((int)$r['base_power'])?></td><td><?=msw_e($r['activity'])?></td><td><small>REC <?=number_format((int)$r['recoveries'])?> · FOB <?=number_format((int)$r['fob_wins'])?>/<?=number_format((int)$r['fob_attacks'])?> · PvP <?=number_format((int)$r['pvp_wins'])?>/<?=number_format((int)$r['pvp_battles'])?></small></td></tr><?php endforeach;?></tbody></table><?php msw_panel_end();msw_footer(); ?>
