<?php
declare(strict_types=1);
require __DIR__.'/includes/ui.php';
$u=msw_require_user();$uid=(int)$u['id'];msw_recalculate_base($uid);$u=msw_user();
$sectors=msw_all('SELECT * FROM base_sectors WHERE user_id=? ORDER BY score DESC','i',[$uid]);
$bases=msw_mother_base_catalog();$baseKey=(string)($u['mother_base_key']??'land_dirt');if(!isset($bases[$baseKey]))$baseKey='land_dirt';$base=$bases[$baseKey];
$counts=msw_one("SELECT COUNT(*) total,SUM(CASE WHEN unit_class IN ('vehicle','air') THEN 1 ELSE 0 END) hardware FROM units WHERE owner_user_id=?",'i',[$uid]);
$allies=[];
foreach(msw_all('SELECT u.id,u.username,u.base_grade,u.base_power,u.mother_base_key FROM friends f JOIN users u ON u.id=f.friend_user_id WHERE f.user_id=? ORDER BY u.username','i',[$uid]) as $ally)$allies[(int)$ally['id']]=$ally;
$force=msw_one('SELECT strike_force_id FROM strike_force_members WHERE user_id=?','i',[$uid]);
if($force)foreach(msw_all('SELECT u.id,u.username,u.base_grade,u.base_power,u.mother_base_key FROM strike_force_members m JOIN users u ON u.id=m.user_id WHERE m.strike_force_id=? AND u.id<>? ORDER BY u.username','ii',[(int)$force['strike_force_id'],$uid]) as $ally)$allies[(int)$ally['id']]=$ally;
msw_header('Mother Base','base.php');msw_resource_strip($uid);
?>
<section class="hero"><div class="eyebrow">MOTHER BASE COMMAND NETWORK</div><h1>MOTHER BASE <span><?=msw_e($u['base_grade'])?></span></h1><p>Recovered personnel and hardware are permanent roster assets. Assign staff by aptitude to increase sector levels, unlock systems, strengthen FOB defense, and raise total Base Power.</p></section>
<section class="panel physical-base-card" style="margin-top:18px"><div class="physical-base-preview"><img src="<?=msw_e(msw_url($base['image']))?>" alt=""></div><div class="physical-base-copy"><div class="eyebrow">PHYSICAL BASE DEPLOYMENT</div><h2><?=msw_e($base['name'])?></h2><p><?=msw_e($base['type'])?> · <?=msw_e($base['climate'])?> · <?=number_format((int)($counts['total']??0))?> recovered units · <?=number_format((int)($counts['hardware']??0))?> captured hardware.</p><p>Your selected base is a live shared space. Staff patrol its open ground slowly, vehicles remain parked, and established friends or Strike Force members can enter and see the same synchronized garrison.</p><div class="actions"><a class="btn" href="<?=msw_e(msw_url('mother_base.php'))?>">Enter Mother Base</a><a class="btn secondary" href="<?=msw_e(msw_url('profile.php?id='.$uid))?>">Account / Base Selection</a></div></div></section>
<?php if($allies):?><section class="panel" style="margin-top:18px"><div class="panel-head"><div><small>AUTHORIZED VISITATION NETWORK</small><h2>Allied Mother Bases</h2></div><span class="bolts">•••</span></div><div class="panel-body allied-base-list"><?php foreach($allies as $ally):$allyBase=$bases[$ally['mother_base_key']]??$bases['land_dirt'];?><div class="allied-base"><div><b><?=msw_e($ally['username'])?></b><small><?=msw_e($allyBase['name'])?> · <?=msw_e($ally['base_grade'])?> · PWR <?=number_format((int)$ally['base_power'])?></small></div><a class="btn small" href="<?=msw_e(msw_url('mother_base.php?owner='.(int)$ally['id']))?>">Visit Base</a></div><?php endforeach;?></div></section><?php endif;?>
<div class="grid g3" style="margin-top:18px"><?php foreach($sectors as $s):$m=msw_sectors()[$s['sector_key']];?><article class="panel sector"><div class="panel-body"><span class="badge"><?=msw_e($s['grade'])?></span><h3><?=msw_e($m['name'])?></h3><div class="score"><?=number_format((int)$s['score'])?></div><small>LEVEL <?=intval($s['level'])?> · CAPACITY <?=intval($s['capacity'])?></small></div></article><?php endforeach;?></div>
<div class="actions"><a class="btn" href="<?=msw_e(msw_url('staff.php'))?>">Staff Management</a><a class="btn secondary" href="<?=msw_e(msw_url('rd.php'))?>">R&D Laboratory</a><a class="btn secondary" href="<?=msw_e(msw_url('strategic.php'))?>">Strategic Systems</a></div>
<?php msw_footer(); ?>
