<?php
declare(strict_types=1);
require __DIR__.'/includes/ui.php';
$user=msw_require_user();$uid=(int)$user['id'];msw_fob_resolve_due_dispatches($uid,8);msw_bot_simulation_pulse(null,10);
$membership=msw_fob_membership($uid);if(!$membership)msw_redirect('fob_globe.php');
$requestedWorld=(int)($_GET['world']??0);$worldId=$requestedWorld>0?$requestedWorld:(int)$membership['world_id'];$world=msw_fob_world_row($worldId);if(!$world){http_response_code(404);exit('That FOB shard is unavailable.');}
$isHome=$worldId===(int)$membership['world_id'];$biome=msw_fob_biome_catalog()[(string)$world['biome_key']]??null;if(!$biome)throw new RuntimeException('That FOB region is unavailable.');
$skins=msw_fob_skin_catalog();$members=msw_fob_world_members($worldId);$population=count($members);$protected=!empty($user['fob_protection_until'])&&strtotime((string)$user['fob_protection_until'])>time();$pending=msw_one("SELECT COUNT(*) c FROM fob_strike_dispatches WHERE attacker_user_id=? AND result='pending'",'i',[$uid]);
$centerX=$isHome?(int)$membership['x']:1000;$centerY=$isHome?(int)$membership['y']:1000;
msw_header($isHome?'Home FOB Shard':'Enemy FOB Shard','fob.php');msw_alert(msw_flash());msw_resource_strip($uid);
?>
<section class="hero"><div class="eyebrow"><?=$isHome?'HOME FOB SHARD':'REMOTE INVASION SHARD'?> · <?=msw_e(msw_fob_world_name($world))?></div><h1><?=msw_e(strtoupper($biome['theatre']))?> <span>WAR MAP</span></h1><p><?=$isHome?'Your home FOB stays here permanently. Select a rival in this shard, or open the Global FOB Map to invade another region.':'You are scouting another shard without moving your home FOB. Open any rival marker to inspect the target and attack when its shield is down.'?></p></section>
<div class="fob-world-toolbar"><span class="badge">SHARD <?=msw_e(msw_fob_world_name($world))?></span><span class="badge"><?=number_format($population)?> / <?=number_format((int)$world['capacity'])?> FOBs</span><span class="badge"><?=$protected?'YOUR HOME FOB PROTECTED':'YOUR HOME FOB OPEN'?></span><span class="badge"><?=intval($pending['c']??0)?> STRIKE TEAMS ACTIVE</span><a class="btn" href="<?=msw_e(msw_url('fob.php'))?>">Command Centre</a><a class="btn secondary" href="<?=msw_e(msw_url('fob_globe.php'))?>">Global FOB Map</a><a class="btn secondary" href="<?=msw_e(msw_url('fob_infiltration.php?world='.$worldId))?>">Target List</a><a class="btn secondary" href="<?=msw_e(msw_url('fob_dispatch.php'))?>">Strike Operations</a><?php if(!$isHome):?><a class="btn secondary" href="<?=msw_e(msw_url('fob_world.php'))?>">Home Shard</a><?php endif;?></div>
<section class="fob-world-console"><div class="fob-world-console-head"><div><small>FULL-SIZE 2000 × 2000 WAR MAP</small><strong><?=msw_e($biome['name'])?> World · Shard <?=str_pad((string)(int)$world['shard_index'],3,'0',STR_PAD_LEFT)?></strong></div><div class="warzone-readout"><span><?=$isHome?'Home FOB slot '.(intval($membership['slot_index'])+1):'Scouting enemy shard'?></span><b><?=$isHome?'HOME FOB LOCKED':'GLOBAL INVASION ACCESS'?></b></div></div>
<div class="fob-world-viewport" data-fob-world-viewport data-own-x="<?=$centerX?>" data-own-y="<?=$centerY?>"><div class="fob-world-map" style="width:<?=intval($biome['w'])?>px;height:<?=intval($biome['h'])?>px"><img class="fob-overview-level" src="<?=msw_e(msw_url($biome['image']))?>" width="<?=intval($biome['w'])?>" height="<?=intval($biome['h'])?>" alt="<?=msw_e($biome['name'])?> FOB overview">
<?php foreach($members as $member):$skin=$skins[$member['skin_key']]??null;if(!$skin)continue;$isMe=(int)$member['id']===$uid;$isProtected=!empty($member['fob_protection_until'])&&strtotime((string)$member['fob_protection_until'])>time();$tag=(int)$member['is_bot']===1?'AI':'PLAYER';?>
<?php if($isMe):?><div class="fob-world-marker own" data-own-fob style="left:<?=intval($member['x'])?>px;top:<?=intval($member['y'])?>px"><?php else:?><a class="fob-world-marker enemy <?=$isProtected?'protected':''?>" href="<?=msw_e(msw_url('fob_target.php?id='.(int)$member['id'].'&world='.$worldId))?>" style="left:<?=intval($member['x'])?>px;top:<?=intval($member['y'])?>px" title="<?=msw_e($member['username'])?> · <?=msw_e($member['base_grade'])?> · PWR <?=number_format((int)$member['base_power'])?>"><?php endif;?>
<img src="<?=msw_e(msw_url($skin['icon']))?>" width="256" height="171" alt=""><span><b><?=msw_e($isMe?'YOUR FOB':$member['username'])?></b><small><?=$isMe?'HOME BASE':$tag.' · '.msw_e($member['base_grade']).($isProtected?' · PROTECTED':'')?></small></span><?=$isMe?'</div>':'</a>'?><?php endforeach;?>
</div></div><div class="warzone-scroll-hint"><span>◀</span><span>Full-size FOB map · <?=$isHome?'camera centers on your home FOB':'remote shard reconnaissance'?> · scroll to scout rivals</span><span>▶</span></div></section>
<?php msw_footer(); ?>
