<?php
declare(strict_types=1);
require __DIR__.'/includes/ui.php';
$user=msw_require_user();$uid=(int)$user['id'];msw_fob_resolve_due_dispatches($uid,8);
$membership=msw_fob_membership($uid);if(!$membership)msw_redirect('fob_globe.php');
$targetId=(int)($_GET['id']??$_POST['defender_id']??0);$worldId=(int)($_GET['world']??$_POST['world_id']??0);$target=msw_fob_target_row($uid,$targetId,$worldId>0?$worldId:null);
if(!$target){http_response_code(404);exit('FOB target is not available in the selected invasion shard.');}$worldId=(int)$target['world_id'];$world=msw_fob_world_row($worldId);$isHome=$worldId===(int)$membership['world_id'];
if(msw_is_post()){
    msw_verify_post();$action=(string)($_POST['action']??'dispatch');
    if($action==='dispatch'){
        try{$id=msw_fob_launch_staff_dispatch($uid,$targetId,(array)($_POST['units']??[]));msw_flash('Staff invasion team deployed. Dispatch #'.$id.' will resolve from the persisted server timestamp.','success');}
        catch(Throwable $e){msw_flash($e->getMessage(),'error');}
    }
    msw_redirect('fob_target.php?id='.$targetId.'&world='.$worldId);
}
$target=msw_fob_target_row($uid,$targetId,$worldId);$protected=!empty($target['fob_protection_until'])&&strtotime((string)$target['fob_protection_until'])>time();$skin=msw_fob_skin_catalog()[$target['skin_key']]??null;$base=msw_mother_base_catalog()[$target['skin_key']]??null;$units=msw_fob_available_dispatch_units($uid);$pending=msw_fob_pending_dispatch_for_target($uid,$targetId);$security=msw_one("SELECT score,level,grade FROM base_sectors WHERE user_id=? AND sector_key='security'",'i',[$targetId]);
$recent=msw_all('SELECT r.*,a.username attacker,d.username defender FROM fob_raids r JOIN users a ON a.id=r.attacker_user_id JOIN users d ON d.id=r.defender_user_id WHERE (r.attacker_user_id=? AND r.defender_user_id=?) OR (r.attacker_user_id=? AND r.defender_user_id=?) ORDER BY r.id DESC LIMIT 8','iiii',[$uid,$targetId,$targetId,$uid]);
msw_header('Enemy FOB · '.$target['username'],'fob.php');msw_alert(msw_flash());msw_resource_strip($uid);
?>
<section class="hero"><div class="eyebrow"><?= $isHome?'HOME-SHARD TARGET':'CROSS-SHARD TARGET'?> · <?=msw_e($world?msw_fob_world_name($world):'GLOBAL')?> · <?=((int)$target['is_bot']===1)?'AUTONOMOUS COMMANDER':'HUMAN COMMANDER'?></div><h1><?=msw_e(strtoupper($target['username']))?> <span><?=msw_e($target['base_grade'])?></span></h1><p>This FOB is a valid persisted invasion target <?=$isHome?'inside your home shard':'in a remote shard selected through the Global Earth network'?>. Immediate infiltration and 2–4 member staff strikes use the same atomic raid ledger and defender-protection rules.</p></section>
<div class="actions" style="margin-top:14px"><a class="btn secondary" href="<?=msw_e(msw_url('fob_world.php?world='.$worldId))?>">← Selected Shard</a><a class="btn secondary" href="<?=msw_e(msw_url('fob_infiltration.php?world='.$worldId))?>">Target List</a><a class="btn secondary" href="<?=msw_e(msw_url('fob_globe.php'))?>">Global Earth</a></div>
<div class="grid g2" style="margin-top:18px">
<section class="panel fob-target-card"><div class="panel-body"><div class="fob-target-visual"><?php if($skin):?><img src="<?=msw_e(msw_url($skin['icon']))?>" alt=""><?php endif;?></div><div class="actions"><span class="grade"><?=msw_e($target['base_grade'])?></span><?php if((int)$target['is_bot']===1):?><span class="ai-mark">AI FOB #<?=intval($target['bot_index']??0)?></span><?php endif;?><span class="badge"><?=$protected?'PROTECTED':'OPEN FOR INVASION'?></span></div><h2><?=msw_e($base['name']??'Forward Operating Base')?></h2><div class="grid g3"><?php msw_stat('Base Power',number_format((int)$target['base_power']));msw_stat('Security',number_format((int)($security['score']??0)),(string)($security['grade']??'--'));msw_stat('World Slot','X '.intval($target['x']).' · Y '.intval($target['y']));?></div>
<?php if($protected):?><p class="muted-copy">Post-invasion protection expires <span data-countdown="<?=msw_e(date(DATE_ATOM,strtotime((string)$target['fob_protection_until'])))?>"></span> from now.</p><?php else:?><form method="post" action="<?=msw_e(msw_url('fob_attack.php'))?>" class="actions" style="margin-top:14px"><?=msw_csrf_field()?><input type="hidden" name="defender_id" value="<?=$targetId?>"><input type="hidden" name="world_id" value="<?=$worldId?>"><input type="hidden" name="return" value="fob_target.php"><button>Immediate Infiltration</button></form><?php endif;?></div></section>
<section><?php msw_panel('Dispatch Staff Invasion','2–4 AVAILABLE UNITS');?><?php if($pending):?><div class="alert info">A staff invasion is already en route to this FOB. Arrival in <b data-countdown="<?=msw_e(date(DATE_ATOM,strtotime((string)$pending['finish_at'])))?>"></b>.</div><?php endif;?>
<?php if($protected):?><div class="empty">Target is protected. New invasion teams cannot launch until protection expires.</div><?php elseif(count($units)<2):?><div class="empty">At least two non-dispatched staff are required.</div><?php else:?><form method="post" data-fob-dispatch-form data-min="2" data-max="4"><?=msw_csrf_field()?><input type="hidden" name="action" value="dispatch"><input type="hidden" name="defender_id" value="<?=$targetId?>"><input type="hidden" name="world_id" value="<?=$worldId?>"><div class="dispatch-unit-grid"><?php foreach($units as $unit):?><label class="dispatch-unit-card"><input type="checkbox" name="units[]" value="<?=intval($unit['id'])?>"><span><b><?=msw_e($unit['callsign'])?></b><small><?=msw_e($unit['unit_class'])?> · LV <?=intval($unit['level'])?> · <?=msw_e($unit['grade'])?></small><em>COMBAT <?=intval($unit['combat'])?> · SEC <?=intval($unit['security'])?></em></span></label><?php endforeach;?></div><div class="dispatch-submit-row"><span><b data-fob-selected-count>0</b> selected · choose 2–4</span><button data-fob-dispatch-submit disabled>Dispatch Invasion Team</button></div></form><?php endif;?><?php msw_panel_end();?></section>
</div>
<?php msw_panel('Head-to-Head Raid History','PERSISTED REPORTS');?><table><thead><tr><th>Raid</th><th>Direction</th><th>Result</th><th></th></tr></thead><tbody><?php foreach($recent as $r):?><tr><td>#<?=intval($r['id'])?></td><td><?=msw_e($r['attacker'])?> → <?=msw_e($r['defender'])?></td><td><?=msw_e(str_replace('_',' ',$r['result']))?></td><td><a class="btn small secondary" href="<?=msw_e(msw_url('fob_result.php?id='.(int)$r['id']))?>">Report</a></td></tr><?php endforeach;?></tbody></table><?php if(!$recent):?><div class="empty">No previous raids between these FOBs.</div><?php endif;?><?php msw_panel_end();?></section>
<?php msw_footer(); ?>
