<?php
declare(strict_types=1);
require __DIR__.'/includes/ui.php';
$user=msw_require_user();$uid=(int)$user['id'];msw_fob_resolve_due_dispatches($uid,8);msw_bot_simulation_pulse(null,8);
$ownProtection=msw_fob_commander_protection($uid);$membership=msw_fob_membership($uid);if(!$membership)msw_redirect('fob_globe.php');$worldId=(int)($_GET['world']??0);if($worldId<=0)$worldId=(int)$membership['world_id'];$world=msw_fob_world_row($worldId);if(!$world){http_response_code(404);exit('FOB world unavailable.');}$isHome=$worldId===(int)$membership['world_id'];$targets=msw_fob_targets_in_world($uid,$worldId,144);
$history=msw_all('SELECT r.*,a.username attacker,d.username defender FROM fob_raids r JOIN users a ON a.id=r.attacker_user_id JOIN users d ON d.id=r.defender_user_id WHERE r.attacker_user_id=? OR r.defender_user_id=? ORDER BY r.id DESC LIMIT 16','ii',[$uid,$uid]);
msw_header('FOB Infiltration Network','fob.php');msw_alert(msw_flash());msw_resource_strip($uid);
?>
<section class="hero"><div class="eyebrow">FORWARD OPERATING BASE NETWORK · <?=msw_e(msw_fob_world_name($world))?> · <?=$isHome?'HOME':'REMOTE'?></div><h1>FOB <span>INFILTRATION</span></h1><p>Target authority is global across populated shards. This legacy shard ledger remains available for focused reconnaissance, while the FOB Command Centre now coordinates priority targeting, parallel staff invasions and retaliation. Any successfully committed offense drops your own active protection.</p></section>
<div class="actions" style="margin-top:14px"><a class="btn" href="<?=msw_e(msw_url('fob.php'))?>">Command Centre</a><a class="btn secondary" href="<?=msw_e(msw_url('fob_world.php?world='.$worldId))?>">← Selected Shard</a><a class="btn" href="<?=msw_e(msw_url('fob_globe.php'))?>">Global Earth</a><a class="btn secondary" href="<?=msw_e(msw_url('fob_dispatch.php'))?>">Staff Strike Ledger</a></div>
<div class="grid g2" style="margin-top:18px"><section><?php msw_panel('Available FOB Targets',$isHome?'HOME SHARD':'CROSS-SHARD');?>
<table><thead><tr><th>Commander</th><th>Grade</th><th>Power</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($targets as $target):$protected=!empty($target['fob_protection_until'])&&strtotime((string)$target['fob_protection_until'])>time();?><tr><td><a href="<?=msw_e(msw_url('fob_target.php?id='.(int)$target['id'].'&world='.$worldId))?>"><?=msw_e($target['username'])?></a> <?=((int)$target['is_bot']===1)?'<span class="ai-mark">AI FOB</span>':''?></td><td><span class="grade"><?=msw_e($target['base_grade'])?></span></td><td><?=number_format((int)$target['base_power'])?></td><td><?=$protected?'PROTECTED':'OPEN'?></td><td><form method="post" action="<?=msw_e(msw_url('fob_attack.php'))?>" <?=$ownProtection&&!$protected?'data-breaks-protection="1"':''?>><?=msw_csrf_field()?><input type="hidden" name="defender_id" value="<?=intval($target['id'])?>"><input type="hidden" name="world_id" value="<?=$worldId?>"><input type="hidden" name="return" value="fob_infiltration.php"><button class="small" <?=$protected?'disabled':''?>>Infiltrate</button></form></td></tr><?php endforeach;?></tbody></table><?php if(!$targets):?><div class="empty">No rival FOBs occupy this instance yet.</div><?php endif;?><?php msw_panel_end();?></section>
<section><?php msw_panel('Raid Ledger','RECENT ACTIVITY');?><table><thead><tr><th>Match</th><th>Result</th><th>Report</th></tr></thead><tbody><?php foreach($history as $raid):?><tr><td><?=msw_e($raid['attacker'])?> → <?=msw_e($raid['defender'])?></td><td><span class="badge"><?=msw_e(str_replace('_',' ',$raid['result']))?></span></td><td><a class="btn small secondary" href="<?=msw_e(msw_url('fob_result.php?id='.(int)$raid['id']))?>">Report</a></td></tr><?php endforeach;?></tbody></table><?php msw_panel_end();?></section></div>
<?php msw_footer(); ?>
