<?php
declare(strict_types=1);
require __DIR__.'/includes/pvp_engine.php';
require_once __DIR__.'/includes/ui.php';
$u=msw_require_user();$uid=(int)$u['id'];$id=(int)($_GET['id']??$_POST['id']??0);
if(msw_is_post()){
    msw_verify_post();$version=(int)($_POST['version']??0);$move=(string)($_POST['move']??'rifle_burst');
    try{$result=msw_pvp_commit_turn($id,$uid,$version,$move);if($result['mode']==='snapshot'&&$result['status']==='active')msw_pvp_process_bot_turn($id,true);}catch(Throwable $e){msw_flash($e->getMessage(),'warning');}
    msw_redirect('pvp_match.php?id='.$id);
}
$m=msw_one('SELECT p.*,u1.username p1,u2.username p2,u1.character_key c1,u2.character_key c2,u1.is_bot b1,u2.is_bot b2 FROM pvp_matches p JOIN users u1 ON u1.id=p.player1_id JOIN users u2 ON u2.id=p.player2_id WHERE p.id=? AND (p.player1_id=? OR p.player2_id=?)','iii',[$id,$uid,$uid]);
if(!$m){http_response_code(404);exit('PvP match not found.');}
$s=json_decode((string)$m['state_json'],true);$me=$s['fighters'][(string)$uid];$otherId=$uid===(int)$m['player1_id']?(int)$m['player2_id']:(int)$m['player1_id'];$foe=$s['fighters'][(string)$otherId];
$chars=msw_character_catalog();$myChar=$chars[$uid===(int)$m['player1_id']?$m['c1']:$m['c2']]??reset($chars);$foeChar=$chars[$uid===(int)$m['player1_id']?$m['c2']:$m['c1']]??reset($chars);$foeBot=$uid===(int)$m['player1_id']?(int)$m['b2']===1:(int)$m['b1']===1;
msw_header('Live PvP Match','pvp.php');msw_alert(msw_flash());
?>
<div data-pvp-watch data-pvp-id="<?=intval($id)?>" data-pvp-version="<?=intval($m['version'])?>" data-pvp-state-url="<?=msw_e(msw_url('pvp_state.php?id='.$id))?>"><div class="grid g2"><section><?php msw_panel($m['p1'].' vs '.$m['p2'],'MATCH #'.$id.' · '.strtoupper(str_replace('_',' ',(string)$m['match_mode'])));?><div class="battle-scene"><div class="fighter player"><img src="<?=msw_e(msw_url($myChar['sprite']))?>" alt=""><div class="battle-card"><b><?=msw_e($me['name'])?> · Lv <?=intval($me['level'])?></b><div class="hpbar"><i style="width:<?=max(0,min(100,round(100*$me['hp']/$me['max_hp'])))?>%"></i></div><small>HP <?=intval($me['hp'])?> / <?=intval($me['max_hp'])?></small></div></div><div class="fighter"><img src="<?=msw_e(msw_url($foeChar['sprite']))?>" alt=""><div class="battle-card"><b><?=msw_e($foe['name'])?> · Lv <?=intval($foe['level'])?> <?=$foeBot?'· AI':''?></b><div class="hpbar"><i style="width:<?=max(0,min(100,round(100*$foe['hp']/$foe['max_hp'])))?>%"></i></div><small>HP <?=intval($foe['hp'])?> / <?=intval($foe['max_hp'])?></small></div></div></div><?php msw_panel_end();?></section><section><?php msw_panel('Live Battle Channel','VERSION '.intval($m['version']));?><div class="battle-log"><?php foreach(array_reverse(array_slice($s['log'],-12)) as $line):?><div><?=msw_e($line)?></div><?php endforeach;?></div>
<?php if($m['status']==='active'):?><p><?=intval($m['current_turn_user_id'])===$uid?'<span class="grade">YOUR TURN</span>':($foeBot?'<span class="ai-mark">AI TURN · SERVER PROCESSING</span>':'Waiting for opponent turn…')?></p><?php if((int)$m['current_turn_user_id']===$uid):?><form method="post"><?=msw_csrf_field()?><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="version" value="<?=intval($m['version'])?>"><select name="move"><?php foreach(msw_move_catalog() as $k=>$mv):?><option value="<?=msw_e($k)?>"><?=msw_e($mv['name'])?> · <?=msw_e($mv['type'])?></option><?php endforeach;?></select><button style="margin-top:8px">Commit Turn</button></form><?php else:?><p><small><?=$foeBot?'The autonomous commander chooses and commits a tactical action server-side.':'The live channel is watching for the opponent\'s committed turn.'?></small></p><?php endif;?>
<?php else:?><div class="alert success">Match resolved: <?=msw_e(strtoupper(str_replace('_',' ',$m['status'])))?>. Both commanders receive persistent XP; recovered personnel are never permanently lost.</div><a class="btn" href="<?=msw_e(msw_url('pvp.php'))?>">PvP Network</a><?php endif;msw_panel_end();?></section></div></div><?php msw_footer(); ?>
