<?php
declare(strict_types=1);require __DIR__.'/includes/battle_engine.php';require_once __DIR__.'/includes/ui.php';$u=msw_require_user();$uid=(int)$u['id'];$id=(int)($_GET['id']??$_POST['id']??0);if($id<=0)msw_redirect('map_select.php');$flash=null;
if(msw_is_post()){
 msw_verify_post();$version=(int)($_POST['version']??0);$db=msw_db();$db->begin_transaction();$consoleEvents=[];
 try{
  $row=msw_one("SELECT * FROM encounters WHERE id=? AND user_id=? FOR UPDATE",'ii',[$id,$uid]);
  if(!$row||$row['status']!=='active'||(int)$row['version']!==$version){$db->rollback();msw_flash('Battle state changed in another request. Refreshed safely.','warning');msw_redirect('battle.php?id='.$id);}
  $s=json_decode((string)$row['state_json'],true,512,JSON_THROW_ON_ERROR);msw_sync_commander_battle_state($uid,$s);msw_sync_enemy_runtime_state($s);$action=(string)($_POST['action']??'');
  if($action==='attack'){
   $moveKey=(string)($_POST['move']??'rifle_burst');$moves=msw_move_catalog();$moveName=(string)($moves[$moveKey]['name']??$moves['rifle_burst']['name']??'Attack');
   msw_battle_attack($s,$moveKey);
   $consoleEvents[]=['COMBAT','ATTACK',$moveName.' against '.(string)($s['enemy']['name']??'target').'.',['encounter_id'=>$id,'move'=>$moveName,'enemy_hp'=>(int)($s['enemy']['hp']??0),'round'=>(int)($s['round']??0)]];
  }elseif($action==='recover'){
   $itemKey=(string)($_POST['item']??'fulton');$fultonCatalog=msw_fulton_catalog();$systemName=(string)($fultonCatalog[$itemKey]['name']??$itemKey);
   [$ok,$msg]=msw_try_recovery($uid,$s,$itemKey);$flash=['message'=>$msg,'kind'=>$ok?'success':'warning'];
   if($msg==='Recovery successful.'||$msg==='Recovery failed.') $consoleEvents[]=['RECOVERY',$ok?'SUCCESS':'FAILED',($ok?'Recovered ':'Recovery attempt failed on ').(string)($s['enemy']['name']??'target').' using '.$systemName.'.',['encounter_id'=>$id,'target'=>(string)($s['enemy']['name']??'target'),'system'=>$systemName]];
  }elseif($action==='retreat'){
   if($s['context']==='field'){$s['finished']=true;$s['result']='retreated';$consoleEvents[]=['COMBAT','RETREAT','Retreated from '.(string)($s['enemy']['name']??'field engagement').'.',['encounter_id'=>$id]];}
   else $flash=['message'=>'Retreat is unavailable in this operation.','kind'=>'error'];
  }
  $resolved=null;
  if(!empty($s['finished'])){$resolved=(string)($s['result']??'lost');msw_finalize_battle($uid,$id,$s);}else msw_stmt('UPDATE encounters SET state_json=?,version=version+1 WHERE id=? AND user_id=?','sii',[json_encode($s,JSON_UNESCAPED_SLASHES),$id,$uid]);
  $db->commit();
  if($resolved!==null)$consoleEvents[]=['COMBAT','RESOLVED','Engagement '.$resolved.' against '.(string)($s['enemy']['name']??'target').'.',['encounter_id'=>$id,'result'=>$resolved,'context'=>(string)($s['context']??'field'),'context_key'=>(string)($s['context_key']??''),'enemy'=>(string)($s['enemy']['name']??'target')]];
  foreach($consoleEvents as $evt)msw_console_event_for_user($uid,$evt[0],$evt[1],$evt[2],$evt[3]);
 }catch(Throwable $e){$db->rollback();throw $e;}
}
$row=msw_one('SELECT * FROM encounters WHERE id=? AND user_id=?','ii',[$id,$uid]);if(!$row){http_response_code(404);exit('Battle not found.');}$s=json_decode((string)$row['state_json'],true);if($row['status']==='active'){msw_sync_commander_battle_state($uid,$s);msw_sync_enemy_runtime_state($s);}$inv=msw_inventory($uid);$enemy=$s['enemy'];$player=$s['player'];$ec=msw_enemy_catalog()[$enemy['key']]??null;msw_header('Combat Engagement');if(!$flash)$flash=msw_flash();msw_alert($flash);?>
<div class="grid g2"><section><?php msw_panel(ucfirst((string)$s['context']).' Engagement','TURN '.(int)$s['round']);?><div class="battle-scene"><div class="fighter player"><img src="<?=msw_e(msw_url((msw_character_catalog()[$u['character_key']]??reset(msw_character_catalog()))['sprite']))?>" alt=""><div class="battle-card"><b><?=msw_e($player['name'])?> · Lv <?=intval($player['level'])?></b><div class="hpbar"><i style="width:<?=max(0,min(100,round(100*$player['hp']/$player['max_hp'])))?>%"></i></div><small>HP <?=intval($player['hp'])?> / <?=intval($player['max_hp'])?> · <?=msw_e($player['class'])?></small></div></div><div class="fighter enemy enemy-<?=msw_e((string)$enemy['class'])?>"><img src="<?=msw_e(msw_url($enemy['sprite']))?>" alt=""><div class="battle-card"><b><?=msw_e($enemy['name'])?> · Lv <?=intval($enemy['level'])?></b><div class="hpbar"><i style="width:<?=max(0,min(100,round(100*$enemy['hp']/$enemy['max_hp'])))?>%"></i></div><small>HP <?=intval($enemy['hp'])?> / <?=intval($enemy['max_hp'])?> · <?=msw_e($enemy['class'])?></small></div></div></div><?php msw_panel_end();?></section>
<section><?php msw_panel('Combat Console','SERVER AUTHORITY');?><div class="battle-log"><?php foreach(array_reverse(array_slice($s['log'],-12)) as $line):?><div><?=msw_e($line)?></div><?php endforeach;?></div><?php if($row['status']==='active'):?><form method="post" style="margin-top:12px"><?=msw_csrf_field()?><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="version" value="<?=intval($row['version'])?>"><div class="field"><label>Attack Pattern</label><select name="move"><?php foreach(msw_move_catalog() as $k=>$m):?><option value="<?=msw_e($k)?>"><?=msw_e($m['name'])?> · <?=msw_e($m['type'])?> · PWR <?=intval($m['power'])?></option><?php endforeach;?></select></div><div class="actions"><button name="action" value="attack">Execute Attack</button><?php if((int)$enemy['recruitable']):?><button class="secondary" name="action" value="recover">Attempt Recovery</button><?php endif;?><?php if($s['context']==='field'):?><button class="danger" name="action" value="retreat">Retreat</button><?php endif;?></div><?php if((int)$enemy['recruitable']):?><div class="field" style="margin-top:10px"><label>Fulton System</label><select name="item"><?php foreach(msw_fulton_catalog() as $k=>$f):?><option value="<?=msw_e($k)?>"><?=msw_e($f['name'])?> · x<?=intval($inv[$k]??0)?> · R&D <?=intval($f['rd'])?></option><?php endforeach;?></select><small style="color:#919b86">Recovery probability increases sharply as target HP falls. Class eligibility and R&D are validated server-side.</small></div><?php endif;?></form><?php else:?><?php $resultKind=$row['status']==='lost'?'warning':'success';$continuePage=match((string)$s['context']){'field'=>'map.php?zone='.urlencode((string)$s['context_key']),'boss'=>'bosses.php','sidequest'=>'sidequests.php','trainer'=>'commanders.php',default=>'missions.php'}; ?><div class="alert <?=$resultKind?>" style="margin-top:12px">Engagement complete: <?=msw_e(strtoupper((string)$row['status']))?>. Your operative and recovered roster return fully combat-ready after the engagement.</div><div class="actions"><a class="btn" href="<?=msw_e(msw_url($continuePage))?>">Continue</a><a class="btn secondary" href="<?=msw_e(msw_url('base.php'))?>">Mother Base</a></div><?php endif;?><?php msw_panel_end();?></section></div><?php msw_footer();?>
