<?php
declare(strict_types=1);

return [
    'name' => 'Metal Slug Warzone',
    'version' => '0.8.6.1',
    'timezone' => 'Australia/Melbourne',
    'db' => [
        'host' => getenv('MSW_DB_HOST') ?: '127.0.0.1',
        'port' => (int)(getenv('MSW_DB_PORT') ?: 3306),
        'name' => getenv('MSW_DB_NAME') ?: 'metal_slug_warzone',
        'user' => getenv('MSW_DB_USER') ?: 'root',
        'pass' => '',
        'charset' => 'utf8mb4',
    ],
    'presence_ttl_seconds' => 45,
    'movement_min_interval_ms' => 80,
    'encounter_chance' => 7,
    'strategic_project_seconds' => 86400,
    'dispatch_tick_seconds' => 60,
    'fob_attack_cooldown_seconds' => 0,
    'fob_staff_dispatch_seconds' => 120,
    'fob_defender_protection_seconds' => 900,
    'world_pulse_interval_ms' => 2000,
    'world_arrival_batch_size' => 4,
    'world_arrival_time_budget_ms' => 120,
    'bot_population_enabled' => true,
    'bot_population_size' => 1000,
    'bot_presence_limit_per_map' => 240,
    'bot_action_min_seconds' => 4,
    'bot_action_max_seconds' => 11,
    'bot_pulse_budget_multiplier' => 1.25,
    'bot_pulse_max_budget' => 8,
    'bot_request_hard_cap' => 4,
    'bot_request_time_budget_ms' => 180,
    'bot_catchup_max_operations' => 8,
    'bot_competitive_anchor_power' => 3500,
    'bot_human_invasion_bias_percent' => 28,
    'bot_roster_cap' => 48,
];
